[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "trade_flow"
version = "0.0.1"
authors = [
  {name="Fred Thomas", email="fred.thomas@eci.ox.ac.uk"},
  {name="Tom Russell", email="tom.russell@ouce.ox.ac.uk"},
]
description = "Helper package for trade flow workflow"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
